# run_test_program:
#   image: nixos/nix:latest
#   script:
#     - nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command ./test.sh

run_test_program_python_quick:
  parallel:
    matrix:
      - algorithms: "vi"
  resource_group: lock
  image: python
  script:
    - python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout 10

run_test_program_python_parallel:
  parallel:
    matrix:
      - algorithms: 
        - "vi"
        only:
        - "beb"
        - "blocksworld"
        - "cdrive"
        - "consensus"
        - "csma"
        - "eajs"
        - "echoring"
        - "elevators"
        - "exploding-blocksworld"
        - "firewire"
        - "firewire_abst"
        - "firewire_dl"
        - "pacman"
        - "philosophers-mdp"
        - "pnueli-zuck"
        - "rabin"
        - "rectangle-tireworld"
        - "tireworld"
        - "triangle-tireworld"
        - "wlan"
        - "wlan_dl"
        - "zenotravel"
        - "zeroconf"
        - "zeroconf_dl"
  resource_group: lock
  image: python
  script:
    - echo "Running tests for $algorithms with only $only"
    - python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout 600 --parallel --only $only