# run_test_program:
#   image: nixos/nix:latest
#   script:
#     - nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command ./test.sh

run_test_program_python:
  parallel:
    matrix:
      - algorithms: "vi"
        timeout: 10
        parallel: false
      - algorithms: "vi"
        timeout: 1800
        parallel: true
  # lock so that the ci not times out if multiple branches run jobs in parallel
  resource_group: $algorithms-$parallel-$timeout
  image: python
  script:
    - |
      if [ "$parallel" = "true" ]; then
        python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout $timeout --parallel
      else
        python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout $timeout
      fi