run_test_program_python_quick:
  parallel:
    matrix:
      - algorithms:
        - "vi"
        - "pi"
        - "smt"
  resource_group: lock
  image: python
  script:
    - pip install -r requirements.txt
    - python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout 10

run_test_program_python_parallel:
  parallel:
    matrix:
      - algorithms: 
        - "vi"
        - "pi"
        - "smt"
        only:
        - "beb"
        - "blocksworld"
        - "cdrive"
        - "consensus"
        - "csma"
        - "eajs"
        - "echoring"
        - "elevators"
        - "exploding-blocksworld"
        - "firewire"
        - "firewire_abst"
        - "firewire_dl"
        - "pacman"
        - "philosophers-mdp"
        - "pnueli-zuck"
        - "rabin"
        - "rectangle-tireworld"
        - "tireworld"
        - "triangle-tireworld"
        - "wlan"
        - "wlan_dl"
        - "zenotravel"
        - "zeroconf"
        - "zeroconf_dl"
  resource_group: lock
  image: python
  script:
    - echo "Running tests for $algorithms with only $only"
    - pip install -r requirements.txt
    - mkdir -p results
    - python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout 60 --only $only