# run_test_program:
#   image: nixos/nix:latest
#   script:
#     - nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command ./test.sh

run_test_program_python:
  image: python
  script:
    - pip install -r requirements.txt
    - python src/model_checker/test.py "modest"