# run_test_program:
#   image: nixos/nix:latest
#   script:
#     - nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command ./test.sh

run_test_program_python:
  parallel:
    matrix:
      - algorithms: "vi"
      - algorithms: "pi"
  # lock so that the ci not times out if multiple branches run jobs in parallel
  resource_group: $algorithms
  image: python
  script:
    - python src/model_checker/test.py --modest-path "modest" --algorithms $algorithms --timeout 60